# Generated by Django 3.1.5 on 2022-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
